import type { Metadata } from 'next'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import "./globals.css";

export const metadata: Metadata = {
  title: 'Resumivise',
  description: 'Generated by Pooria Taghdiri',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col min-h-screen">
      <Header/>
      <body>{children}</body>
      <Footer/>
    </div>
  )
}